name: Renovate

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v38.9.0
        with:
          token: ${{ secrets.GH_TOKEN }}
